name: Licensing compliance

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Verify REUSE compliance
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5
